// AUTO-GENERATED by generate.ps1 — do not edit by hand.
window.PLAYABLES = [
  {
    "slug": "amd-housebuilder",
    "title": "AMD_HouseBuilder",
    "url": "amd-housebuilder/index.html",
    "type": "html",
    "thumb": "amd-housebuilder/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2026-08-15"
  },
  {
    "slug": "noizepad",
    "title": "NoizePad",
    "url": "noizepad/index.html",
    "type": "html",
    "thumb": "noizepad/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2026-08-15"
  },
  {
    "slug": "block-chpok",
    "title": "Block Chpok",
    "url": "block-chpok/index.html",
    "type": "html",
    "thumb": "block-chpok/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2026-04-18"
  },
  {
    "slug": "da-pbsleepthief",
    "title": "DA_PbSleepThief",
    "url": "da-pbsleepthief/index.html",
    "type": "html",
    "thumb": "da-pbsleepthief/screenshot.jpg",
    "project": {
      "name": "Days After",
      "shortName": "DA",
      "appStore": "https://apps.apple.com/app/id1498731586",
      "googlePlay": "https://play.google.com/store/apps/details?id=games.alternativa.projectv.test"
    },
    "tags": [],
    "details": "",
    "created": "2026-03-07"
  },
  {
    "slug": "wr-pbclicker-repair",
    "title": "WR_PbClicker-Repair",
    "url": "wr-pbclicker-repair/index.html",
    "type": "html",
    "thumb": "wr-pbclicker-repair/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2026-02-12"
  },
  {
    "slug": "hc-flappy-dragon",
    "title": "HC Flappy Dragon",
    "url": "hc-flappy-dragon/index.html",
    "type": "html",
    "thumb": "hc-flappy-dragon/screenshot.jpg",
    "project": {
      "name": "Hustle Castle",
      "shortName": "HC",
      "appStore": "https://apps.apple.com/us/app/id1154402178",
      "googlePlay": "https://play.google.com/store/apps/details?id=com.my.hc.rpg.kingdom.simulator"
    },
    "tags": [
      "construct3"
    ],
    "details": "",
    "created": "2026-01-06"
  },
  {
    "slug": "hc-runner",
    "title": "HC Runner",
    "url": "hc-runner/index.html",
    "type": "html",
    "thumb": "hc-runner/screenshot.jpg",
    "project": null,
    "tags": [
      "construct3"
    ],
    "details": "",
    "created": "2026-01-06"
  },
  {
    "slug": "hc-minigame-puzzle1",
    "title": "HC_MiniGame_Puzzle1",
    "url": "hc-minigame-puzzle1/index.html",
    "type": "html",
    "thumb": "hc-minigame-puzzle1/screenshot.jpg",
    "project": {
      "name": "Hustle Castle",
      "shortName": "HC",
      "appStore": "https://apps.apple.com/us/app/id1154402178",
      "googlePlay": "https://play.google.com/store/apps/details?id=com.my.hc.rpg.kingdom.simulator"
    },
    "tags": [
      "construct3"
    ],
    "details": "",
    "created": "2026-01-06"
  },
  {
    "slug": "lts-fps-playable-3d",
    "title": "LTS Fps playable 3d",
    "url": "lts-fps-playable-3d/index.html",
    "type": "html",
    "thumb": "lts-fps-playable-3d/screenshot.jpg",
    "project": null,
    "tags": [
      "threejs"
    ],
    "details": "",
    "created": "2026-01-06"
  },
  {
    "slug": "mashroom-wars-2-3d",
    "title": "Mashroom Wars 2 (3d)",
    "url": "mashroom-wars-2-3d/index.html",
    "type": "html",
    "thumb": "mashroom-wars-2-3d/screenshot.jpg",
    "project": null,
    "tags": [
      "pixijs"
    ],
    "details": "",
    "created": "2026-01-06"
  },
  {
    "slug": "tacticool-3d-gameplay",
    "title": "Tacticool 3d Gameplay",
    "url": "tacticool-3d-gameplay/index.html",
    "type": "html",
    "thumb": "tacticool-3d-gameplay/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2026-01-01"
  },
  {
    "slug": "hc-match-three-drinks",
    "title": "HC Match Three drinks",
    "url": "hc-match-three-drinks/index.html",
    "type": "html",
    "thumb": "hc-match-three-drinks/screenshot.jpg",
    "project": {
      "name": "Hustle Castle",
      "shortName": "HC",
      "appStore": "https://apps.apple.com/us/app/id1154402178",
      "googlePlay": "https://play.google.com/store/apps/details?id=com.my.hc.rpg.kingdom.simulator"
    },
    "tags": [
      "pixijs",
      "dragon",
      "bones"
    ],
    "details": "",
    "created": "2025-12-30"
  },
  {
    "slug": "road-warrior",
    "title": "Road Warrior",
    "url": "road-warrior/index.html",
    "type": "html",
    "thumb": "road-warrior/screenshot.jpg",
    "project": null,
    "tags": [
      "prototype"
    ],
    "details": "",
    "created": "2025-12-30"
  },
  {
    "slug": "zc-casemania",
    "title": "ZC_CaseMania",
    "url": "zc-casemania/index.html",
    "type": "html",
    "thumb": "zc-casemania/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2025-12-30"
  },
  {
    "slug": "castlebuilder",
    "title": "CastleBuilder",
    "url": "castlebuilder/index.html",
    "type": "html",
    "thumb": "castlebuilder/screenshot.jpg",
    "project": {
      "name": "Hustle Castle",
      "shortName": "HC",
      "appStore": "https://apps.apple.com/us/app/id1154402178",
      "googlePlay": "https://play.google.com/store/apps/details?id=com.my.hc.rpg.kingdom.simulator"
    },
    "tags": [],
    "details": "",
    "created": "2025-12-23"
  },
  {
    "slug": "goh-customize-3d",
    "title": "GoH_Customize_3d",
    "url": "goh-customize-3d/index.html",
    "type": "html",
    "thumb": "goh-customize-3d/screenshot.jpg",
    "project": {
      "name": "Guild Of Heroes",
      "shortName": "GoH",
      "appStore": "",
      "googlePlay": "https://play.google.com/store/apps/details?id=com.goplaytoday.guildofheroes"
    },
    "tags": [
      "3d",
      "Threejs"
    ],
    "details": "Customize hero cloth and face",
    "created": "2025-12-23"
  },
  {
    "slug": "littlebigrobots",
    "title": "LittleBigRobots",
    "url": "littlebigrobots/index.html",
    "type": "html",
    "thumb": "littlebigrobots/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2025-12-23"
  },
  {
    "slug": "spaceminer",
    "title": "SpaceMiner",
    "url": "spaceminer/index.html",
    "type": "html",
    "thumb": "spaceminer/screenshot.jpg",
    "project": null,
    "tags": [],
    "details": "",
    "created": "2025-12-23"
  },
  {
    "slug": "towerbuilder",
    "title": "TowerBuilder",
    "url": "towerbuilder/index.html",
    "type": "html",
    "thumb": "towerbuilder/screenshot.jpg",
    "project": {
      "name": "Hustle Castle",
      "shortName": "HC",
      "appStore": "https://apps.apple.com/us/app/id1154402178",
      "googlePlay": "https://play.google.com/store/apps/details?id=com.my.hc.rpg.kingdom.simulator"
    },
    "tags": [
      "2d",
      "construct",
      "3"
    ],
    "details": "",
    "created": "2025-12-23"
  },
  {
    "slug": "war-robots-playable",
    "title": "War Robots Playable",
    "url": "war-robots-playable/index.html",
    "type": "html",
    "thumb": "war-robots-playable/screenshot.jpg",
    "project": null,
    "tags": [
      "3d",
      "threejs"
    ],
    "details": "",
    "created": "2025-12-23"
  },
  {
    "slug": "zc-chemicalsuit",
    "title": "ZC_ChemicalSuit",
    "url": "zc-chemicalsuit/index.html",
    "type": "html",
    "thumb": "zc-chemicalsuit/screenshot.jpg",
    "project": null,
    "tags": [
      "2d",
      "Construct",
      "3"
    ],
    "details": "",
    "created": "2025-12-23"
  },
  {
    "slug": "zombie-shooter-playable",
    "title": "Zombie Shooter Playable",
    "url": "zombie-shooter-playable/index.html",
    "type": "html",
    "thumb": "zombie-shooter-playable/screenshot.jpg",
    "project": {
      "name": "Days After",
      "shortName": "DA",
      "appStore": "https://apps.apple.com/app/id1498731586",
      "googlePlay": "https://play.google.com/store/apps/details?id=games.alternativa.projectv.test"
    },
    "tags": [
      "threejs",
      "3d"
    ],
    "details": "",
    "created": "2025-12-23"
  }
];
