<#
  Regenerates catalog.js by scanning playable folders in this directory.

  How to add a new playable:
    1. Create a new folder here (use a url-safe name, e.g. my-cool-playable).
    2. Put the playable inside as index.html (or an .html / .zip file).
    3. Put a preview image as screenshot.jpg (or screenshot.png).
    4. (optional) Add meta.json for title / project / tags / details.
    5. Run:  pwsh ./generate.ps1
  index.html reads catalog.js, so the gallery updates automatically.

  Folders starting with "_" or "." are ignored.
#>

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$items = @()

Get-ChildItem -Path $root -Directory |
  Where-Object { $_.Name -notmatch '^[_\.]' } |
  Sort-Object Name |
  ForEach-Object {
    $dir  = $_
    $slug = $dir.Name
    $meta = @{}
    $metaPath = Join-Path $dir.FullName 'meta.json'
    if (Test-Path $metaPath) {
      $meta = Get-Content $metaPath -Raw -Encoding UTF8 | ConvertFrom-Json
    }

    # playable file: meta.playable -> index.html -> first .html -> first .zip
    $playable = $meta.playable
    if (-not $playable) {
      if (Test-Path (Join-Path $dir.FullName 'index.html')) { $playable = 'index.html' }
      else {
        $html = Get-ChildItem $dir.FullName -Filter *.html -File | Select-Object -First 1
        if ($html) { $playable = $html.Name }
        else {
          $zip = Get-ChildItem $dir.FullName -Filter *.zip -File | Select-Object -First 1
          if ($zip) { $playable = $zip.Name }
        }
      }
    }
    if (-not $playable) { Write-Warning "skip '$slug': no playable file"; return }

    $type = $meta.playableType
    if (-not $type) { $type = if ($playable -match '\.zip$') { 'zip' } else { 'html' } }

    # screenshot: meta.screenshot -> screenshot.* -> first image
    $shot = $meta.screenshot
    if (-not $shot -or -not (Test-Path (Join-Path $dir.FullName $shot))) {
      $img = Get-ChildItem $dir.FullName -File |
             Where-Object { $_.Extension -match '\.(jpg|jpeg|png|webp|gif)$' -and $_.BaseName -match 'screenshot' } |
             Select-Object -First 1
      if (-not $img) {
        $img = Get-ChildItem $dir.FullName -File |
               Where-Object { $_.Extension -match '\.(jpg|jpeg|png|webp|gif)$' } | Select-Object -First 1
      }
      if ($img) { $shot = $img.Name }
    }

    $title = if ($meta.title) { $meta.title } else { $slug }
    $tags  = @(); if ($meta.tags) { $tags = @($meta.tags) }
    $proj  = $null
    if ($meta.project) {
      $proj = [ordered]@{
        name       = $meta.project.name
        shortName  = $meta.project.shortName
        appStore   = $meta.project.appStore
        googlePlay = $meta.project.googlePlay
      }
    }

    $items += [ordered]@{
      slug      = $slug
      title     = $title
      url       = "$slug/$playable"
      type      = $type
      thumb     = if ($shot) { "$slug/$shot" } else { $null }
      project   = $proj
      tags      = $tags
      details   = if ($meta.details) { $meta.details } else { '' }
      created   = if ($meta.created) { $meta.created } else { '' }
    }
  }

# newest first (by created date string yyyy-MM-dd), untitled dates sink to bottom
$items = $items | Sort-Object @{ Expression = { $_.created }; Descending = $true }, @{ Expression = { $_.title } }

$json = ($items | ConvertTo-Json -Depth 6)
if ($items.Count -eq 1) { $json = "[`n$json`n]" }   # ConvertTo-Json unwraps single-element arrays
if ($items.Count -eq 0) { $json = "[]" }

$out = "// AUTO-GENERATED by generate.ps1 — do not edit by hand.`r`nwindow.PLAYABLES = $json;`r`n"
Set-Content -Path (Join-Path $root 'catalog.js') -Value $out -Encoding UTF8 -NoNewline

Write-Host "catalog.js written: $($items.Count) playables"
